version: '3.8'

services:
  postgres-pharmacy:
    image: postgres:15-alpine
    container_name: pillpulse-pharmacy-db
    environment:
      POSTGRES_DB: pharmacy_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 20031217
    ports:
      - "5432:5432"
    volumes:
      - postgres_pharmacy_data:/var/lib/postgresql/data

  postgres-medicine:
    image: postgres:15-alpine
    container_name: pillpulse-medicine-db
    environment:
      POSTGRES_DB: medicine_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 20031217
    ports:
      - "5433:5432"
    volumes:
      - postgres_medicine_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: pillpulse-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"      # AMQP port (services connect here)
      - "15672:15672"    # Management UI (browser)
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  postgres_pharmacy_data:
  postgres_medicine_data:
  rabbitmq_data: