server:
  port: 8080

spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/pillpulse
          jwk-set-uri: http://localhost:8180/realms/pillpulse/protocol/openid-connect/certs

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true
          routes:
            - id: pharmacy-service
              uri: lb://pharmacy-service
              predicates:
                - Path=/api/pharmacies/**

            - id: medicine-service
              uri: lb://medicine-service
              predicates:
                - Path=/api/medicines/**

            - id: search-service
              uri: lb://search-service
              predicates:
                - Path=/api/search/**

            - id: alert-service
              uri: lb://alert-service
              predicates:
                - Path=/api/alerts/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG